@CS_API_HostAddress = http://localhost:5073


### Get all configurations
GET {{CS_API_HostAddress}}/configurations/
Accept: application/json
###

### Post a new configuration (JSON object)
POST {{CS_API_HostAddress}}/configurations/
Content-Type: application/json

[
  {
    "snmpPolls": [
      {
        "name": "SwitchSNMP",
        "id": 2345234523452345234,
        "ip": "192.168.10.20",
        "hostname": "Switch-1",
        "oids": [
          {
            "oid": "1.3.6.1.4.1.9.2.1.56.0",
            "name": "CPU LOAD"
          },
          {
            "oid": "1.3.6.1.4.1.9.2.1.8.0",
            "name": "Memory Usage"
          },
          {
            "oid": "1.3.6.1.2.1.1.3.0",
            "name": "Uptime"
          }
        ],
        "user": "MY-USER",
        "authentication": "SHA1",
        "encryption": "aes 128",
        "authpass": "MyAuthPass",
        "privpass": "MyPrivPass",
        "port": 161
      }
    ]
  },
  {
    "netflowReceiver": [
      {
        "name": "Netflow1",
        "id": 12312,
        "folderLocation": "/home/cyberscape_admin/Netflow_example_files",
        "nfdumpBinaryLocation": "/usr/bin/nfdump",
        "nfcapdBinaryLocation": "/usr/bin/nfcapd",
        "port": 2055
      }
    ]
  },
  {
    "Syslog": [
      {
        "name": "Sys1",
        "id": 56756,
        "port": 514
      }
    ]
  },
  {
    "ScyllaDB": {
      "port": 123,
      "ipaddresses": 12312
    }
  }
]


###

### POST A NEW CONFIGURATION (TEST OF RESTARTING)
POST {{CS_API_HostAddress}}/configurations/
Content-Type: application/json

[
  {
    "Syslog": [
      {
        "name": "Sys1",
        "id": 56756,
        "port": 514
      }
    ]
  }
]

### POST A NEW CONFIGURATION (TEST OF RESTARTING (SYSLOG TRAP ONLY))
POST {{CS_API_HostAddress}}/configurations/
Content-Type: application/json

[
   {
      "snmpPolls":[
         {
            "name":"FG-SNMP",
            "id":123123,
            "ip":"10.0.1.254",
            "hostname":"FG-SNMP",
            "oids":[
               {
                  "oid":"1.3.6.1.4.1.12356.101.4.1.3.0",
                  "name":"CPU LOAD"
               },
               {
                  "oid":"1.3.6.1.2.1.47.1.2.1.1.2.1",
                  "name":"Device"
               },
               {
                  "oid":"1.3.6.1.4.1.12356.101.4.1.4.0",
                  "name":"MEMORY USAGE"
               },
               {
                  "oid":"1.3.6.1.2.1.1.3.0",
                  "name":"UPTIME"
               },
               {
                  "oid":"1.3.6.1.4.1.12356.101.4.1.1.0",
                  "name":"VERSION"
               },
               {
                  "oid":"1.3.6.1.4.1.12356.101.7.2.2.1.1.x",
                  "name":"VLANS"
               },
               {
                  "oid":"1.3.6.1.4.1.12356.101.3.2.1.1.7.x",
                  "name":"SESSION COUNT"
               },
               {
                  "oid":"1.3.6.1.2.1.47.1.1.1.1.14.x",
                  "name":"INTERFACES"
               },
               {
                  "oid":"1.3.6.1.2.1.4.20.1.3.x",
                  "name":"Subnetmask"
               },
               {
                  "oid":"1.3.6.1.2.1.4.20.1.1.x",
                  "name":"IpAdd"
               },
               {
                  "oid":"1.3.6.1.2.1.31.1.1.1.1.x",
                  "name":"All Interfaces"
               },
               {
                  "oid":"1.3.6.1.2.1.31.1.1.1.10.x",
                  "name":"Sent Traffic/Interface"
               },
               {
                  "oid":"1.3.6.1.2.1.31.1.1.1.6.x",
                  "name":"Received Traffic/Interface"
               },
               {
                  "oid":"1.3.6.1.2.1.4.20.1.2.x",
                  "name":"All_Interface_IPs"
               },
               {
                  "oid":"1.3.6.1.4.1.12356.101.5.1.2.1.1.1.x",
                  "name":"Polcy-IDs"
               },
               {
                  "oid":"1.3.6.1.4.1.12356.101.5.1.2.1.1.3.x",
                  "name":"Bytes pro Policy"
               },
               {
                  "oid":"1.3.6.1.4.1.12356.101.5.1.2.1.1.2.x",
                  "name":"Matches pro Policy"
               },
                {
                  "oid":"1.3.6.1.4.1.12356.101.5.1.2.1.1.4.x",
                  "name":"Latest Match of Policy"
               },
               {
                  "oid":"1.3.6.1.4.1.12356.101.4.1.8.0",
                  "name":"Session Count"
               }
            ],
            "user":"MY-USER",
            "authentication":"SHA1",
            "encryption":"AES128",
            "authpass":"MyAuthPass",
            "privpass":"MyPrivPass",
            "port":161
         },
         {
            "name":"CS-Catalyst",
            "id":98273045,
            "ip":"10.0.200.10",
            "hostname":"CS-Catalyst",
            "oids":[
               {
                  "oid":"1.3.6.1.2.1.1.3.0",
                  "name":"SysUpTime"
               },
               {
                  "oid":"1.3.6.1.2.1.2.2.1.2.x",
                  "name":"Interface Name"
               },
               {
                  "oid":"1.3.6.1.2.1.2.2.1.7.x",
                  "name":"Interface Admin Status"
               },
               {
                  "oid":"1.3.6.1.2.1.2.2.1.8.x",
                  "name":"Interface Operational Status"
               },
               {
                  "oid":"1.3.6.1.2.1.4.20.1.1.x",
                  "name":"IP Address"
               },
               {
                  "oid":"1.3.6.1.2.1.4.20.1.2.x",
                  "name":"Interface to IP Mapping"
               },
               {
                  "oid":"1.3.6.1.2.1.17.4.3.1.2.x",
                  "name":"MAC Address to Port Mapping"
               },
               {
                  "oid":"1.3.6.1.2.1.17.2.15.1.5.x",
                  "name":"Spanning Tree Port State"
               },
               {
                  "oid":"1.3.6.1.2.1.31.1.1.1.6.x",
                  "name":"Interface In Octets"
               },
               {
                  "oid":"1.3.6.1.4.1.9.2.1.58.0",
                  "name":"CPU Utilization (5s)"
               },
               {
                  "oid":"1.3.6.1.2.1.31.1.1.1.10.x",
                  "name":"Interface Out Octets"
               },
               {
                  "oid":"1.3.6.1.2.1.47.1.1.1.1.9.1001",
                  "name":"IOS-Version"
               },
               {
                  "oid":"1.3.6.1.2.1.47.1.1.1.1.13.1001",
                  "name":"Switch-Model"
               },
               {
                  "oid":"1.3.6.1.4.1.9.9.48.1.1.1.5.x",
                  "name" : "Used Memory"
               },
               {
                  "oid":"1.3.6.1.4.1.9.2.1.8.0",
                  "name" : "Free Memory in Bytes"
                }
               
            ],
            "user":"MY-USER",
            "authentication":"SHA1",
            "encryption":"AES128",
            "authpass":"MyAuthPass",
            "privpass":"MyPrivPass",
            "port":161
         },
         {
            "name":"CS-MirrorCatalyst",
            "id":12394780,
            "ip":"10.0.1.99",
            "hostname":"CS-MirrorCatalyst",
            "oids":[
               {
                  "oid":"1.3.6.1.2.1.1.3.0",
                  "name":"SysUpTime"
               },
               {
                  "oid":"1.3.6.1.4.1.9.2.1.58.0",
                  "name":"CPU Utilization (5s)"
               },
               {
                  "oid":"1.3.6.1.4.1.9.2.1.8.0",
                  "name":"Free Memory"
               },
               {
                  "oid":"1.3.6.1.2.1.2.2.1.2.x",
                  "name":"Interface Name"
               },
               {
                  "oid":"1.3.6.1.2.1.2.2.1.7.x",
                  "name":"Interface Admin Status"
               },
               {
                  "oid":"1.3.6.1.2.1.2.2.1.8.x",
                  "name":"Interface Operational Status"
               },
               {
                  "oid":"1.3.6.1.2.1.4.20.1.1.x",
                  "name":"IP Address"
               },
               {
                  "oid":"1.3.6.1.2.1.4.20.1.2.x",
                  "name":"Interface to IP Mapping"
               },
               {
                  "oid":"1.3.6.1.2.1.17.4.3.1.2.x",
                  "name":"MAC Address to Port Mapping"
               },
               {
                  "oid":"1.3.6.1.2.1.17.2.15.1.5.x",
                  "name":"Spanning Tree Port State"
               },
               {
                  "oid":"1.3.6.1.2.1.31.1.1.1.6.x",
                  "name":"Interface In Octets"
               },
               {
                  "oid":"1.3.6.1.2.1.31.1.1.1.10.x",
                  "name":"Interface Out Octets"
               },
               {
                  "oid":"1.3.6.1.2.1.47.1.1.1.1.9.1001",
                  "name":"IOS-Version"
               },
               {
                  "oid":"1.3.6.1.2.1.47.1.1.1.1.13.1001",
                  "name":"Switch-Model"
               },
               {
                  "oid":"1.3.6.1.4.1.9.9.48.1.1.1.5.x",
                  "name" : "Used Memory"
               },
               {
                  "oid":"1.3.6.1.4.1.9.2.1.8.0",
                  "name" : "Free Memory in Bytes"
                }
            ],
            "user":"MY-USER",
            "authentication":"SHA1",
            "encryption":"AES128",
            "authpass":"MyAuthPass",
            "privpass":"MyPrivPass",
            "port":161
         }
      ]
   },
   {
      "netflowReceiver":[
         {
            "name":"Netflow1",
            "id":12312,
            "folderLocation":"/home/cyberscape_admin/Netflow_example_files",
            "nfdumpBinaryLocation":"/usr/bin/nfdump",
            "nfcapdBinaryLocation":"/usr/bin/nfcapd",
            "port":2055
         }
      ]
   },
   {
      "Syslog":[
         {
            "name":"Sys1",
            "id":56756,
            "port":514
         }
      ]
   },
   {
      "snmpTrapReceiver":[
         {
            "name":"SNMP-Trap-Receiver",
            "id":123123,
            "port":162
         }
      ]
   }
]

### GET HOST ASSIGNMENT
GET {{CS_API_HostAddress}}/host_assignment/


### POST A NEW Host Assignment (TEST OF RESTARTING (SYSLOG TRAP ONLY))
POST {{CS_API_HostAddress}}/host_assignment/
Content-Type: application/json

{
  "assignments": [
    {
      "hostname": "Fortinet Fortigate",
      "ipAddress": "10.0.1.254",
      "device_type": "Firewall"
    },
    {
      "hostname": "SIEM",
      "ipAddress": "10.0.1.10",
      "device_type": "Server"
    },
    {
      "hostname": "LOG-GENERATOR",
      "ipAddress": "192.168.30.30",
      "device_type": "FirServer"
    },
    {
      "hostname": "WebGui",
      "ipAddress": "10.0.1.150",
      "device_type": "Server"
    }
  ]
}
### GET ALERTS
GET {{CS_API_HostAddress}}/alerts/
Accept: application/json

### POST A NEW ALERT
POST {{CS_API_HostAddress}}/alerts/
Content-Type: application/json

{
    "id": 1,
    "name": "SYSLOG_SEVERITY_7",
    "tabelle": "syslog",
    "condition": "severity=7",
    "email_adresse": "0148@htl.rennewg.at",
    "custom_message": "OH WEH OH WEH ES GIBT EINEN SYSLOG MIT LEVEL7"
    "timestamp": ""
}
### POST A NEW ALERT
POST {{CS_API_HostAddress}}/alerts/
Content-Type: application/json

{
    "id": 2,
    "name": "SYSLOG_SEVERITY_1",
    "tabelle": "syslog",
    "condition": "severity=1",
    "email_adresse": "0148@htl.rennewg.at",
    "custom_message": "OH WEH OH WEH ES GIBT EINEN SYSLOG MIT LEVEL 1",
    "timestamp": ""
}


### POST A WRONG NEW ALERT
POST {{CS_API_HostAddress}}/alerts/
Content-Type: application/json

{
  "id": 123123,
  "name": "NAME2",
  "tabelle": "SNMP",
  "condition": "1.2.45.56 = 1",
  "custom_message": "Test Nachricht 2"
  
}

### DELETE AN ALERT
DELETE {{CS_API_HostAddress}}/alerts/1

### QUERY SERVER TEST
GET http://10.0.1.200:8000/database/syslog?sd=2025-02-17&st=11:07:00&et=23:59:59&severity=0
Accept: application/json



### QUERY SERVER TEST
GET http://10.0.1.200:8000/database/syslog?severity=7&sd=2025-2-1&st=15:10:6&et=23:59:59
Accept: application/json

### QUERY AP TEST
GET https://10.0.1.254/api/v2/monitor/wifi/managed_ap
Accept: application/json
Authorization: Bearer HNrmjsgr9z9Q44rf3N1pzh8zr9kgrr


### QUERY AP TEST
GET {{CS_API_HostAddress}}/host_assignment/
Accept: application/json

### WRONG HOST ASSIGNMENT
POST {{CS_API_HostAddress}}/host_assignment/
Content-Type: application/json

{
  "assignments": [
    {
      "hostname": "localhost",
      "ipAddress": "127.0.0.1"
    }
    
  ]
}


### GET SNMP DATA
GET http://10.40.21.154:8000/database/snmp?lb=0&ub=1&sd=2025-02-19&st=00:45:51&et=20:50:00&ed=2025-02-19&lb=0&ub=1&oid=1.3.6.1.4.1.12356.101.7.2.2.1.1.%
Accept: application/json