@CS_API_HostAddress = http://localhost:5073



### Get all configurations
GET {{CS_API_HostAddress}}/configurations/
Accept: application/json
###

### Post a new configuration (JSON object)
POST {{CS_API_HostAddress}}/configurations/
Content-Type: application/json

[
  {
    "snmpPolls": [
      {
        "name": "SwitchSNMP",
        "id": 2345234523452345234,
        "ip": "192.168.10.20",
        "hostname": "Switch-1",
        "oids": [
          {
            "oid": "1.3.6.1.4.1.9.2.1.56.0",
            "name": "CPU LOAD"
          },
          {
            "oid": "1.3.6.1.4.1.9.2.1.8.0",
            "name": "Memory Usage"
          },
          {
            "oid": "1.3.6.1.2.1.1.3.0",
            "name": "Uptime"
          }
        ],
        "user": "MY-USER",
        "authentication": "SHA1",
        "encryption": "aes 128",
        "authpass": "MyAuthPass",
        "privpass": "MyPrivPass",
        "port": 161
      }
    ]
  },
  {
    "netflowReceiver": [
      {
        "name": "Netflow1",
        "id": 12312,
        "folderLocation": "/home/cyberscape_admin/Netflow_example_files",
        "nfdumpBinaryLocation": "/usr/bin/nfdump",
        "nfcapdBinaryLocation": "/usr/bin/nfcapd",
        "port": 2055
      }
    ]
  },
  {
    "Syslog": [
      {
        "name": "Sys1",
        "id": 56756,
        "port": 514
      }
    ]
  },
  {
    "ScyllaDB": {
      "port": 123,
      "ipaddresses": 12312
    }
  }
]


###

### POST A NEW CONFIGURATION (TEST OF RESTARTING)
POST {{CS_API_HostAddress}}/configurations/
Content-Type: application/json

[
  {
    "snmpTrapReceiver": [
      {
        "port": 162,
        "name": "SNMP-Trap-Receiver",
        "id": 456
      }
    ]
  },
  {
    "Syslog": [
      {
        "name": "Sys1",
        "id": 56756,
        "port": 514
      }
    ]
  }
]

### POST A NEW CONFIGURATION (TEST OF RESTARTING (SYSLOG TRAP ONLY))
POST {{CS_API_HostAddress}}/configurations/
Content-Type: application/json

[
  {
    "Syslog": [
      {
        "name": "Sys1",
        "id": 56756,
        "port": 514
      }
    ]
  }
]
### POST A NEW Host Assignment (TEST OF RESTARTING (SYSLOG TRAP ONLY))
POST {{CS_API_HostAddress}}/host_assignment/
Content-Type: application/json

{
  "assignments": [
    {
      "hostname": "localhost",
      "ipAddress": "127.0.0.1"
    },
    {
      "hostname": "WindowsClient1",
      "ipAddress": "10.40.21.155"
    },
    {
      "hostname": "Fortinet Fortigate",
      "ipAddress": "10.0.1.254"
    },
    {
      "hostname": "SIEM",
      "ipAddress": "10.0.1.10"
    },
    {
      "hostname": "LOG GENERATOR",
      "ipAddress": "192.168.30.30"
    },
    {
      "hostname": "WINDOWS NOCH EIN HOST",
      "ipAddress": "192.168.10.1"
    }
  ]
}


### GET ALERTS
GET {{CS_API_HostAddress}}/alerts/
Accept: application/json

### POST A NEW ALERT
POST {{CS_API_HostAddress}}/alerts/
Content-Type: application/json

{
    "id": 123,
    "name": "NAME2",
    "tabelle": "SNMP",
    "condition": "1.2.45.56 = 1",
    "email_adresse": "email@htl.rennewg.at",
    "custom_message": "Test Nachricht 2",
    "timestamp": "WIRD IM BACKEND HINZUGEFUEGT"
  }


### POST A WRONG NEW ALERT
POST {{CS_API_HostAddress}}/alerts/
Content-Type: application/json

{
  "id": 123123,
  "name": "NAME2",
  "tabelle": "SNMP",
  "condition": "1.2.45.56 = 1",
  "email_adresse": "email@htl.rennewg.at",
  "custom_message": "Test Nachricht 2"
  
}

### DELETE AN ALERT
DELETE {{CS_API_HostAddress}}/alerts/123

### QUERY SERVER TEST
GET http://10.0.1.200:8000/database/syslog?sd=2025-01-19&st=13:00:00&et=23:59:59&ip=10.0.1.254&severity=6
Accept: application/json



### QUERY SERVER TEST
GET http://10.0.1.200:8000/database/syslog?severity=7&sd=2025-2-1&st=15:10:6&et=23:59:59
Accept: application/json

### QUERY AP TEST
GET https://10.0.1.254/api/v2/monitor/wifi/managed_ap
Accept: application/json
Authorization: Bearer HNrmjsgr9z9Q44rf3N1pzh8zr9kgrr



